 /**
 * 列表模板
 * @author fanmingfei
 * @date 2015-02-10
 * @version 1.0.0
 */
var tmpl = {

    listTpl: [
    	'<li class="item" aid="<%=aid%>">',
            '<header class="item-header">',
                '<img src="/static/ldsn-wap/lib/img/topic.png" class="user-topic"/>',
                '<section class="article-info">',
                    '<section class="article-from">',
                        '<em><%=username%>',
                    '</section>',
                    '<time><%=time%></time>',
                '</section>',
            '</header>',
            '<h2 class="article-title">',
                '<%=title%>',
            '</h2>',
            '<%if (image) {%>',
            '<img src="<%=image%>" class="article-image"/>',
            '<%}%>',
            '<article class="article-description">',
                '<%=description%>',
            '</article>',
            '<section class="article-handle-info">',
                '<ul>',
                    '<li>',
                        '<i class="thumbs up icon"></i>',
                        '<em><%=favour%></em>',
                    '</li>',
                    '<li>',
                        '<i class="edit sign icon"></i>',
                        '<em><%=comment%></em>',
                    '</li>',
                '</ul>',
            '</section>',
            '<footer class="article-footer">',
                '<section class="article-handle">',
                    '<click class="favour handle active">',
                        '<i class="thumbs up icon"></i>',
                        '<em class="opa">赞</em>',
                    '</click>',
                    '<click class="share handle share-click">',
                        '<i class="share icon"></i>',
                        '<em class="opa" aid="<%=aid%>">分享</em>',
                    '</click>',
                '</section>',
                '<section class="comment" id="comment-<%=id%>">',
                    '<ul class="article-comment">',
                    '<%if(cominfo){%>',
                        '<%for(var i=0;i<cominfo.length;i++){%>',
                            '<li class="comment-item" comment-id="<%=cominfo[i].id%>">',
                                '<img src="/static/ldsn-wap/lib/img/topic.png" alt="<%=cominfo[i].uid%>" class="comment-topic">',
                                '<section class="comment-detail">',
                                    '<section class="coment-info">',
                                        '<time class="comment-time"><%=ldev.timeFormat(cominfo[i].time)%></time>',
                                        '<section class="coment-user-info">',
                                            '<%=cominfo[i].uid%>',
                                        '</section>',
                                    '</section>',
                                    '<section class="comment-content">',
                                        '<%=cominfo[i].content%>',
                                    '</section>',
                                '</section>',
                            '</li>',
                        '<%}%>',
                    '<%}%>',
                    '</ul>',
                    '<section class="edit-comment">',
                        '<click class="submit">',
                            '<i class="reply mail icon"></i>',
                        '</click>',
                        '<section class="input">',
                            '<input aid="" type="text" />',
                        '</section>',
                    '</section>',
                '</section>',
            '</footer>',
        '</li>'
    ],
    comTpl: [
    ]


}

module.exports = tmpl;